# fly.toml app configuration file generated for xiv-proxy on 2023-06-23T12:54:37-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "xiv-proxy"
primary_region = "phx"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
